Description: Udacity Cloud DevOps Engineer Nanodegree Program - Challenge AWS IaC Networking Architecture

Parameters:
  
  ParamMainVPCCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.0.0/16

  ParamPublicSubnetCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.1.0/24

  ParamPrivateSubnetCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.2.0/24

Resources:

  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ParamMainVPCCIRD
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: MainVPC

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: InternetGateway
    Properties:
      VpcId: !Ref MainVPC
      InternetGatewayId: !Ref InternetGateway

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: InternetGateway
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: !Ref ParamPrivateSubnetCIRD
      MapPublicIpOnLaunch: true

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: !Ref ParamPublicSubnetCIRD
      MapPublicIpOnLaunch: true

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NAT:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP
      SubnetId: !Ref PublicSubnet
