Description: Udacity Cloud DevOps Engineer Nanodegree Program - Challenge AWS IaC Networking Architecture

Parameters:
  
  ParamMainVPCCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.0.0/16

  ParamPublicSubnetCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.1.0/24

  ParamPrivateSubnetCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.2.0/24

Resources:

  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ParamMainVPCCIRD

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: InternetGateway
    Properties:
      VpcId: !Ref MainVPC
      InternetGatewayId: !Ref InternetGateway

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: InternetGateway
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: !Ref ParamPrivateSubnetCIRD
      MapPublicIpOnLaunch: false

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: !Ref ParamPublicSubnetCIRD
      MapPublicIpOnLaunch: true

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NAT:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref PublicSubnet

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC

  AssociatePrivateRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  AssociatePublicRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  PrivateInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      NatGatewayId: !Ref NAT
      DestinationCidrBlock: 0.0.0.0/0

  PublicInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
